model:
  random_state: 42
  test_size: 0.2
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 6

paths:
  raw_data_path: data/raw/insurance.csv
  processed_data_path: data/processed/processed.csv
  model_save_path: models/model.pkl
